In [4]:
import json
import pandas as pd
from pathlib import Path

In [6]:
json_path = Path.cwd().parent / 'data' / 'raw' / 'alerts_combined.json'
df = pd.read_json(json_path)
df["fecha"] = (
    pd.to_datetime(df["ts"], unit="s")
    .dt.tz_localize("UTC")
    .dt.tz_convert("America/Mexico_City")
)

/var/folders/2p/1ktczv851yj3pmytrycx6r5m0000gn/T/ipykernel_17368/2832156510.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["fecha"] = (

In [ ]:
#sre del 26 de mayo al 11 de junio 2025
# cx con ts -> 14 al 15 de marzo 2025
# cx con timestamp 24 al 27 de marzo 2026

In [33]:
df[(df.service == 'data-team')]

,ts,timestamp,source,priority,service,condition,threshold,policy,incidents,channel,error_type,error_message,fecha
4,1.749631e+09,2025-06-11 02:36:38-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>60%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-06-11 02:36:38.335369110-06:00
62,1.749484e+09,2025-06-09 09:48:27-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>55%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-06-09 09:48:27.293049097-06:00
120,1.749373e+09,2025-06-08 02:48:34-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>55%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-06-08 02:48:34.539509058-06:00
232,1.748805e+09,2025-06-01 07:27:39-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>55%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-06-01 13:14:19-06:00
334,1.748382e+09,2025-05-27 19:36:33-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>55%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-05-27 15:36:33-06:00
339,1.748334e+09,2025-05-27 05:36:45-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>60%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-05-27 02:16:45-06:00
350,1.748320e+09,2025-05-27 00:27:31-06:00,New Relic,critical,data-team,RDS CPU Usage gral,>60%/10min,Golden Signals,2.0,sre,NaN,NaN,2025-05-26 22:27:31-06:00

In [37]:
df[df.service.isin(['tesseract', 'Cerberus', 'Princess', 'Kraken'])]

,ts,timestamp,source,priority,service,condition,threshold,policy,incidents,channel,error_type,error_message,fecha
0,1.749647e+09,2025-06-11 07:09:39-06:00,New Relic,high,Princess,High Application Response Time gral,>1800ms/5min,Golden Signals,1.0,sre,NaN,NaN,2025-06-11 07:09:39.517959118-06:00
1,1.749643e+09,2025-06-11 05:55:05-06:00,New Relic,critical,Cerberus,High Application Error percentage,baseline/10min,Golden Signals,1.0,sre,NaN,NaN,2025-06-11 05:55:05.830949068-06:00
2,1.749643e+09,2025-06-11 05:54:15-06:00,New Relic,critical,tesseract,Low Application Throughput,baseline/10min,Golden Signals,1.0,sre,NaN,NaN,2025-06-11 05:54:15.028158903-06:00
3,1.749639e+09,2025-06-11 04:43:34-06:00,New Relic,critical,Cerberus,Low Application Throughput,baseline/10min,Golden Signals,1.0,sre,NaN,NaN,2025-06-11 04:43:34.938539028-06:00
8,1.749611e+09,2025-06-10 21:07:48-06:00,New Relic,high,Cerberus,Cerberus Throughput High,>3500/5min,Golden Signals,1.0,sre,NaN,NaN,2025-06-10 21:07:48.880398989-06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,1.748405e+09,2025-05-28 02:10:44-06:00,New Relic,critical,Cerberus,High Application Error percentage,baseline/10min,Golden Signals,1.0,sre,NaN,NaN,2025-05-27 22:10:44-06:00
328,1.748388e+09,2025-05-27 21:12:35-06:00,New Relic,high,tesseract,Throughput high general,>2700/5min,Golden Signals,1.0,sre,NaN,NaN,2025-05-27 17:12:35-06:00
332,1.748383e+09,2025-05-27 20:11:35-06:00,New Relic,critical,Cerberus,Cerberus Throughput High,>3500/5min,Golden Signals,2.0,sre,NaN,NaN,2025-05-27 16:01:35-06:00
346,1.748322e+09,2025-05-27 02:12:38-06:00,New Relic,critical,Cerberus,High Application Error percentage,baseline/10min,Golden Signals,1.0,sre,NaN,NaN,2025-05-26 23:02:38-06:00
358,1.748301e+09,2025-05-26 20:07:52-06:00,New Relic,critical,Cerberus,Cerberus Throughput High,>3500/5min,Golden Signals,3.0,sre,NaN,NaN,2025-05-26 17:10:52-06:00